### PR TITLE
Fastq io fix

### PR DESCRIPTION
**Pull request by austinr1028**
This should significantly speed up reading fastq sequences, as it is now done with a memory map. The PR#21 at the top of the files means Pull Request #21. This will make it easier to track our notes with certain pull requests.

Additionally, I was having some file io errors with some .sci and .scs files when I built using the makefile. Using my IDE everything was fine. Would you be able to test this and see if it’s reproducible?

After you approve this and verify that the file io error isn’t happening to you I will push to master.

### CODE REVIEW

**Comment by austinr1028** [comment]
My .scs/.sci file io errors were actually occurring when I used the SQmanager.py script, not a makefile (I didn't even compile with it). I used the binary for my IDE and SQmanager script so I'm not sure what's going on. If you can reproduce let me know!

**Comment by jbohac** [comment]
Hey Austin,

Awesome work, everything looks good!

I wasn't able to test your changes, and I am leaving for the game right now.
I should be able to look at it first thing tomorrow morning

Thanks,
Jacob

**Comment by jbohac** [comment]
I was able to run your changes with no io errors. Should be good to merge

**Comment by austinr1028** [comment]
Ok. I will push to master then and we can start branching from that. I’ll be working on the Dictionary stuff today.

**Comment by jbohac** [comment]
Ok great. I made changes to bitCompress, I will get that in later today and
start running some larger test sets

**Pull request merged**
